spring:
  application:
    name: db-service

    
server:
  port: 8300


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8302/eureka