   
server:
  port: 8100

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customerstore
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka: 
client: 
service-url: 
defaultZone: http://${eureka.host:http://192.168.99.100}:${eureka.port:8761}/eureka/