spring:
  application:
    name: stock-service

server:
  port: 9090


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8302/eureka